apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: open-webui
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      tolerations:
      - key: "platform"
        operator: "Equal"
        value: "YOUR_NODE_TAINT_VALUE"
        effect: "NoSchedule"
      containers:
      - name: cloudflared
        image: yourorg.azurecr.io/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - $(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: open-webui-secrets
              key: TUNNEL_TOKEN
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
