# PVC for Open WebUI (managed-csi - Azure Disk SSD)
# No PV needed - Azure automatically creates disk
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: open-webui
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 10Gi
