apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  # Refresh secrets from Key Vault every 1 hour
  refreshInterval: 1h

  # Reference to the SecretStore
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-open-webui

  # Target Kubernetes Secret to create
  target:
    name: open-webui-secrets
    creationPolicy: Owner

  # Data to fetch from Azure Key Vault
  data:
  - secretKey: WEBUI_SECRET_KEY
    remoteRef:
      key: webui-secret-key

  - secretKey: MICROSOFT_CLIENT_SECRET
    remoteRef:
      key: openwebui-client-secret

  - secretKey: TUNNEL_TOKEN
    remoteRef:
      key: cf-tunnel-token
