apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: open-webui
  labels:
    app: ollama
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    protocol: TCP
